# 변수(variables)

## 1. type
- int, float
- str, list, tuple, dict
- numpy


In [17]:
a = 1; print(type(a))

<class 'int'>


In [2]:
b = 0.5; type(b)

float

In [1]:
a = 1; a = float(a); print(type(a)) #convert the type

<class 'float'>


In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


##### str : string(문자열)

In [4]:
a = '123'; print(type(a)); print(a[1]); print(a[0]); print(a[-1])

<class 'str'>
2
1
3


In [12]:
a = '123'; type(a) ; type(a[1]) ; a[1]

'2'

##### list

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [22]:
a = [1,'2', [3, '4']] #recursive
print(type(a)); print(a[0]); print(a[1]); print(a[2]) 
print(type(a[-1]))

<class 'list'>
1
2
[3, '4']
<class 'list'>


### tuple[]
* list vs. tuple : list can be changable, while tuple is fixed

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


### dic : dictionary{}

In [24]:
a = {"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [25]:
a=[(1,2,3), (3,8,0)]
print(type(a)); print(a)
print(type(a[1])); print(a[1])

<class 'list'>
[(1, 2, 3), (3, 8, 0)]
<class 'tuple'>
(3, 8, 0)


### numpy
##### - np.array(list?),  numpy.ndrray
##### - np. matrix(ndarray), numpy.matrixlib.defmatrix.matrix

In [27]:
import numpy as np
b = np.array(a) #transform A to a ndarray (similar but different from matrix)
print(b) 
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [28]:
c = np.matrix(b)
print(c) #a 2X3 matrix
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [31]:
print(c.T) #transpose the line and the column, a 3X2 martix
c*c.T 

[[1 3]
 [2 8]
 [3 0]]


matrix([[14, 19],
        [19, 73]])